### ISSUE TITLE
Redistribuição dos cargos da Boitatech

### ISSUE THREAD

**Issue by LuskaBol** [boitatech/estatuto#7]
Por meio dessa issue eu gostaria de solicitar a reformulação e redistribuição dos cargos do servidor Boitatech. Recomendo uma reunião do conselho Tupã para arquitetar tal reforma.

**Comment by beescuit** [comment]
Perfeito. Acredito que seria interessante adicionar o cargo "Moderadores" já que o cargo de voluntários já esta altamente inflado. Como podemos observar, nem todos os "voluntários" estão no grupo da Staff no telegram por exemplo.

A nova estrutura seria composta por:
- Administradores (com o maior numero de permissões)
- Moderadores (permissões basicas como ban/kick, mute e outras relacionadas a chamadas de voz, audit log, etc)
- Voluntários (a discutir, mas pode incluir permissões menos "intrusivas" ao server, assim a gente pode dar esse cargo para mais usuários sem muita preocupação)

**Comment by Luidiblu** [comment]
Não consigo concordar mais com o @beescuit. Creio que devemos subir o cargo de alguns Voluntários para Moderador. 
Dessa forma, iremos abrir mais cargos para voluntários, e elevando horizontalmente as permissões gerais administrativas do Servidor.

**Comment by LuskaBol** [comment]
Muito bem colocado @beescuit. Eu acredito que vale estipular uma métrica objetiva para dizer qual o nível de permissionamento um colaborador da Boitatech deveria ter pela sua participação e disponibilidade para colaborar com a comunidade baseado. Tal métrica deve ser baseada nas atitudes anteriormente demonstradas pelo colaborador.

**Comment by gabriel-vernilo** [comment]
eu concorco com o @beescuit na 1  e 4

**Comment by pr3y** [comment]
eu tambem

**Comment by beescuit** [comment]
ta bom

**Comment by b1scoito** [comment]
Eu acho importante também termos em mente a importância da autonomia dos colaboradores para tomarem as decisões que forem mais adequadas para a manutenção da harmonia da comunidade. Ou seja, é importante que os colaboradores saibam que podem tomar as decisões que forem necessárias para manter o servidor funcionando de forma adequada, sempre que os administradores não estiverem disponíveis para tomar essas decisões.

**Comment by gabriel-vernilo** [comment]
acho que o ideal seria começarmos a levar a sério mesmo kekw

**Comment by G4L1T0** [comment]
Boa noite pessoal,

Vamos organizar uma reunião com todos os voluntários e os administradores para fazer essa redistribuição/configuração dos cargos.

Essa reunião vai acontecer no nosso [discord](https://discord.gg/boitatech), logo mais coloco o dia e o horário aqui nessa issue.

**Comment by Luidiblu** [comment]
Creio que não é preciso colocar o dia e horário da reunião nessa issue. Podemos confirmar e bater certinho com todos os membros da staff via chat da staff no Telegram, já que estamos implementando a feature de issues recentemente e nem todos os membros da staff podem estar acostumados com esse novo workflow.

**Comment by makidelcon** [comment]
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ]

**Comment by c3l3si4n** [comment]
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)

**Comment by c3l3si4n** [comment]
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)
[CLICAR AQUI](https://github.com/c3l3si4n/pugrecon)

**Comment by c3l3si4n** [comment]
obrigado

**Comment by 0xTen** [comment]
https://discord.com/channels/304088484228890644/724854247920762950/992176391594459196 !!!

**Comment by Luidiblu** [comment]
Não consigo concordar mais com a mensagem acima. Olho pra isso com um brilho na retina que olhei pro lado pra garantir  que não tinha nenhuma câmera escondida, eu verifiquei se nenhum staff da Boitatech era o Ivo Holanda porque eu olhava pra essa issue e só se passava uma coisa na minha cabeça: "Isso é bom demais para ser verdade". É uma pepita lapidada por anjos.

**Comment by c3l3si4n** [comment]
> (censurado por galito)

pessoal nao fui censurado foi zoeira 
![image](https://c.tenor.com/zAHCPvoyjNIAAAAC/yay-kitty.gif)
